# DB CONNECTION
spring.datasource.url=jdbc:postgresql://db:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# HIBERNATE
spring.jpa.hibernate.ddl-auto=validate