# DB CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5433/absence_db
spring.datasource.username=trifonas
spring.datasource.password=mypassword

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true